package codex

const (
	codexScanBufferSize = 256 * 1024

	recordTypeSessionMeta  = "session_meta"
	recordTypeTurnContext  = "turn_context"
	recordTypeResponseItem = "response_item"
	recordTypeEventMsg     = "event_msg"

	responseTypeMessage              = "message"
	responseTypeReasoning            = "reasoning"
	responseTypeFunctionCall         = "function_call"
	responseTypeCustomToolCall       = "custom_tool_call"
	responseTypeWebSearchCall        = "web_search_call"
	responseTypeFunctionCallOutput   = "function_call_output"
	responseTypeCustomToolCallOutput = "custom_tool_call_output"
	responseRoleUser                 = "user"
	responseRoleAssistant            = "assistant"
	responseRoleDeveloper            = "developer"
	eventTypeTokenCount              = "token_count"
	eventTypeUserMessage             = "user_message"
	eventTypeAgentMessage            = "agent_message"
	eventTypeAgentReasoning          = "agent_reasoning"
	eventTypeItemCompleted           = "item_completed"
	eventTypeTaskStarted             = "task_started"
	eventTypeTaskComplete            = "task_complete"
	eventTypeTurnAborted             = "turn_aborted"
	eventTypeContextCompacted        = "context_compacted"
	eventItemTypePlan                = "Plan"
	toolNameApplyPatch               = "apply_patch"
	toolNameCloseAgent               = "close_agent"
	toolNameExecCommand              = "exec_command"
	toolNameSendInput                = "send_input"
	toolNameShellCommand             = "shell_command"
	toolNameSpawnAgent               = "spawn_agent"
	toolNameUpdatePlan               = "update_plan"
	toolNameWait                     = "wait"
	toolNameWaitAgent                = "wait_agent"
	toolNameWebSearch                = "web_search"
	toolNameWriteStdin               = "write_stdin"
	commandVerbBuild                 = "build"
	commandVerbRun                   = "run"
	commandVerbTest                  = "test"
	commandRunnerBun                 = "bun"
	commandRunnerNPM                 = "npm"
	commandRunnerPNPM                = "pnpm"
	commandRunnerYarn                = "yarn"
)
